name: Tag Push Workflow

on:
  push:
    tags:
      - 'release*' # Trigger the workflow on push of tags like v1.0, v2.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print a message
        run: echo "A new tag matching the pattern was pushed: ${{ github.ref }}"
